project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - sampler.qmd
    - courses/STAT118/index.qmd
    - courses/STAT118/notes/published/*.qmd

website:
  title: "Casey’s Data Science Extras"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

      - text: "STAT 118: Intro to Data Science"
        href: courses/STAT118/index.qmd
        
      - text: "Samplers"
        href: sampler.qmd
        
  sidebar:
    - id: STAT118
      title: "STAT 118: Intro to Data Science"
      logo: courses/STAT118/images/stat0118_hex_sticker.png
      style: docked
      contents:
        - text: "STAT 118 Home"
          href: courses/STAT118/index.qmd

        - text: "📖 Course Notes"
          class: sidebar-item-group

        - text: "Installing R and RStudio"
          href: courses/STAT118/notes/published/installguide.qmd
          
        - text: "Intro to R & RStudio (Class A)"
          href: courses/STAT118/notes/published/118_A_in_class_notes.qmd
          
        - text: "Data Wrangling Basics (Class B)"
          href: courses/STAT118/notes/published/118_B_wrangling_in_class_notes.qmd
          
        - text: "Manipulating and Summarizing Data (Class C)"
          href: courses/STAT118/notes/published/118_C_aggregating_in_class_notes.qmd
          
        - text: "`ggplot2`: Barplots and Scatterplots (Class D)"
          href: courses/STAT118/notes/published/118_D_ggplot_in_class_notes.qmd



format:
  html:
    theme: 
      - cosmo
      - custom.scss
    
    
execute:
  freeze: auto
