project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - sampler.qmd
    - notes/published/*.qmd

website:
  title: "Casey’s Data Science Extras"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sampler.qmd
        text: Sampler

format:
  html:
    theme: cosmo
    resource-path:
      - .
